use_frameworks!

platform :ios, '9.0'

target 'TensorFlowKit_Example' do
  pod 'TensorFlowKit', :path => '../'

  target 'TensorFlowKit_Tests' do
    inherit! :search_paths

    
  end
end

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
